### ISSUE TITLE
Persistent storage

### ISSUE THREAD

**Issue by aspearman** [aspearman/foundry-aws-beanstalk#3]
Work in #2 means Foundry deploys and runs successfully. But it does not have persistent storage. We want to ensure that new deployments do not mean the website's data is overwritten. The steps to set this up should be documented in the wiki. 

- [ ] Imperatively do it by adding create and mount config files after depending on the existing deployment
- [ ] Make it IAC/declarative by adding custom VPC config in `env.yaml`

**Comment by aspearman** [comment]
We can attach EFS to the environment. See [this post](https://aws.amazon.com/premiumsupport/knowledge-center/elastic-beanstalk-mount-efs-volumes/) and [the docs](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/services-efs.html)

**Comment by aspearman** [comment]
I've gone to EFS in AWS and created one in the default vpc.

**Comment by aspearman** [comment]
In `cfn-init.log` I see:

```
2021-05-29 04:20:39,077 [ERROR] Command 01_mount (/tmp/mount-efs.sh) failed
2021-05-29 04:20:39,077 [ERROR] Error encountered during build of prebuild_0_foundryvtt: Command 01_mount failed
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 573, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 273, in build
    self._config.commands)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command 01_mount failed
2021-05-29 04:20:39,080 [ERROR] -----------------------BUILD FAILED!------------------------
2021-05-29 04:20:39,080 [ERROR] Unhandled exception during build: Command 01_mount failed
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 176, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 135, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 561, in build
    self.run_config(config, worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 573, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 273, in build
    self._config.commands)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command 01_mount failed
```

Going to remove the ebextensions file so work for #7 can progress. Here's the file @adsmith2236 

```
###################################################################################################
#### Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
####
#### Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file
#### except in compliance with the License. A copy of the License is located at
####
####     http://aws.amazon.com/apache2.0/
####
#### or in the "license" file accompanying this file. This file is distributed on an "AS IS"
#### BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#### License for the specific language governing permissions and limitations under the License.
###################################################################################################

###################################################################################################
#### This configuration file mounts an Amazon EFS file system to a directory named /efs. To mount
#### the file system to a different path, modify the MOUNT_DIRECTORY value in the "option_settings"
#### section.
####
#### The FILE_SYSTEM_ID setting references a resource named "FileSystem", which is created by the
#### storage-efs-createfilesystem.config configuration file. To use this file to mount a
#### file system that you created outside of AWS Elastic Beanstalk, replace the Ref with the
#### resource ID (e.g., fs-e7605f4e):
####
####      FILE_SYSTEM_ID: fs-e7605f4e
####
#### If your environment and file system are in a custom VPC, you must configure the VPC to allow
#### DNS resolution and DNS host names. See this topic in the VPC User Guide for more information:
####    http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-dns.html
###################################################################################################

option_settings:
  aws:elasticbeanstalk:application:environment:
    FILE_SYSTEM_ID: 'fs-3abc9302'
    MOUNT_DIRECTORY: '/efs'

##############################################
#### Do not modify values below this line ####
##############################################

packages:
  yum:
    amazon-efs-utils: []

commands:
  01_mount:
    command: "/tmp/mount-efs.sh"

files:
  "/tmp/mount-efs.sh":
      mode: "000755"
      content : |
        #!/bin/bash

        EFS_MOUNT_DIR=$(/opt/elasticbeanstalk/bin/get-config environment -k MOUNT_DIRECTORY)
        EFS_FILE_SYSTEM_ID=$(/opt/elasticbeanstalk/bin/get-config environment -k FILE_SYSTEM_ID)

        echo "Mounting EFS filesystem ${EFS_FILE_SYSTEM_ID} to directory ${EFS_MOUNT_DIR} ..."

        echo 'Stopping NFS ID Mapper...'
        service rpcidmapd status &> /dev/null
        if [ $? -ne 0 ] ; then
            echo 'rpc.idmapd is already stopped!'
        else
            service rpcidmapd stop
            if [ $? -ne 0 ] ; then
                echo 'ERROR: Failed to stop NFS ID Mapper!'
                exit 1
            fi
        fi

        echo 'Checking if EFS mount directory exists...'
        if [ ! -d ${EFS_MOUNT_DIR} ]; then
            echo "Creating directory ${EFS_MOUNT_DIR} ..."
            mkdir -p ${EFS_MOUNT_DIR}
            if [ $? -ne 0 ]; then
                echo 'ERROR: Directory creation failed!'
                exit 1
            fi
        else
            echo "Directory ${EFS_MOUNT_DIR} already exists!"
        fi

        mountpoint -q ${EFS_MOUNT_DIR}
        if [ $? -ne 0 ]; then
            echo "mount -t efs -o tls ${EFS_FILE_SYSTEM_ID}:/ ${EFS_MOUNT_DIR}"
            mount -t efs -o tls ${EFS_FILE_SYSTEM_ID}:/ ${EFS_MOUNT_DIR}
            if [ $? -ne 0 ] ; then
                echo 'ERROR: Mount command failed!'
                exit 1
            fi
            chmod 777 ${EFS_MOUNT_DIR}
            runuser -l  ec2-user -c "touch ${EFS_MOUNT_DIR}/it_works"
            if [[ $? -ne 0 ]]; then
                echo 'ERROR: Permission Error!'
                exit 1
            else
                runuser -l  ec2-user -c "rm -f ${EFS_MOUNT_DIR}/it_works"
            fi
        else
            echo "Directory ${EFS_MOUNT_DIR} is already a valid mountpoint!"
        fi

        echo 'EFS mount complete.'
```

**Comment by aspearman** [comment]
Looks like the best option to initially copy files over to EFS is [mounting the filesystem to your local machine](https://docs.aws.amazon.com/efs/latest/ug/wt1-test.html).

**Comment by aspearman** [comment]
If I'm going to use IAC then it looks like I'll need to create a custom VPC in which to create the EB environment, so that I can specify that custom VPC in the create and mount .config files. See:

>Specify your VPC ID and subnet IDs in the "option_settings" section below. In a custom VPC, use the VPC ID and subnet IDs that you chose for the Amazon EC2 instances running your application. When you create a new environment, you can specify VPC settings in a configuration file with the options in the aws:ec2:vpc namespace. See vpc-custom-loadbalanced.config in the environment_configuration folder for an example.

It looks like I can actually [retrieve the value from the environment](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/ebextensions-functions.html#ebextensions-functions-getoptionsetting) even, so the VPC ID and such aren't even in the config files, so users can easily fork this repo and use their own values.

**Comment by aspearman** [comment]
EFS requires a VPC and the current EB deployment is "not part of a VPC." I suspect it's more like "not part of a **custom** VPC", because the docs say new environments are created in the default VPC by default.

**Comment by aspearman** [comment]
Doesn't seem as though you can create a VPC as part of creating an EB environment. [source](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/vpc.html)

**Comment by aspearman** [comment]
cc @nubuscu

**Comment by aspearman** [comment]
Actually it does seem like you can create a VPC as part of an EB environment. See the docs for [this example file](https://github.com/awsdocs/elastic-beanstalk-samples/blob/master/cfn-templates/vpc-public.yaml)
